services:
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: rag-app
    env_file:
      - .env
    depends_on:
      - ollama
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /Users/macbook/Documents/GenAI/Projects/Data/pdf_data:/Users/macbook/Documents/GenAI/Projects/Data/pdf_data
      - /Users/macbook/Documents/GenAI/Projects/Data/DBs/chroma:/Users/macbook/Documents/GenAI/Projects/Data/DBs/chroma
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  ui:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: rag-ui
    environment:
      API_BASE_URL: http://app:8000
    depends_on:
      - app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app/ui/streamlit_app.py --server.address 0.0.0.0 --server.port 8501

volumes:
  ollama_data:
